jobs:
  build-upload:
    docker:
      - image: docker:19.03.8
    environment:
      IMAGE_NAME: asia.gcr.io/dealio-279907/dealio-backend-vision
    working_directory: /app
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME .

      - run:
          name: Run Test Docker Container
          command: docker run -d --rm $IMAGE_NAME

      - run:
          name: Check Docker Container
          command: docker ps -a
      
      - run:
          name: Delete Docker Container
          command: docker stop $(docker ps -aq)

      - run:
          name: Authentication to Google Container Registry
          command: echo $dealio_gcr_service_account | docker login -u _json_key --password-stdin https://asia.gcr.io

      - run:
          name: Pushing Docker Image to Container Registry
          command: docker push $IMAGE_NAME

workflows:
  version: 2
  build-and-upload:
    jobs:
      - build-upload:
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/